version: '3.8'

services:
  event-bus:
    build: .
    ports:
      - "4305:4305"
    depends_on:
      - mongo

  mongo:
    build: .
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
