version: '3.8'

services:
  post:
    build: .
    ports:
      - "4306:4306"
    depends_on:
      - mongo

  mongo:
    build: .
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
